name: Build and Push project

on:
  push:
    paths:
      - 'project/**'  # Trigger on changes in project folder
      - '.github/workflows/project.yaml'  # Trigger on changes to this workflow file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./project
          push: true
          tags: mohamednabil404/project:${{ github.sha }}  # Use commit SHA as tag

